In [1]:
using LinearAlgebra
using Statistics

In [72]:
# helper methods
function symetric_matrix(dim::Integer)::Matrix
    A = ones(dim,dim);
    for i = 1:dim
        for j = 1:dim
            A[i,j] = rand(1:50);
            A[j,i] = A[i,j];
        end
    end
    return A;
end

function random_matrix(dim::Integer)::Matrix
    A = ones(dim, dim);
    for i = 1:dim
        for j = 1:dim
            A[i,j] = rand(1:50)
        end
    end
    return A
end

function diagonal_matrix(dim::Integer)::Matrix
    I = ones(dim,dim)
    return Diagonal(I)
end

function custom_cond(λₘₐₓ, λₘᵢₙ)
    return √(λₘₐₓ/λₘᵢₙ)
end

custom_cond (generic function with 1 method)

Poniżej przygotowana jest funkcja do metody iteracji prostej (metoda potęgowa), dzięki której można wyznaczyć największą co do modułu wartość własną, czyli promień spektralny macierzy, który opisany jest wzorem:
## $$\rho(A) = |\lambda_{max}| = \lim_{i \to \infty} \frac{||t_{i+1}||_{\infty}}{||t_{i}||_{\infty}}$$

Przy założeniu, że dowolny wektor początkowy t_{0} != 0, do uzyskania promienia spektralnego prowadzą iteracje postaci:
## $$t_{i+1} = At_{i},\ i=0,1,2...$$



In [3]:
# metoda potegowa
function power_eigen(A::Matrix, iterations::Integer)::Array
    n = size(A, 1);
    X = ones(n,1);
    for i = 1:iterations
        X = A * X;
        X = X / norm(X);
    end

    return X' * A * X / (X' * X);
end

function power_eigen_min(A::Matrix, iterations::Integer)::Array
    n = size(A, 1);
    X = ones(n,1);
    for i = 1:iterations
        X = A \ X;
        X = X / norm(X);
    end

    return X' * A * X / (X' * X);
end

power_eigen_min (generic function with 1 method)

In [65]:
A = symetric_matrix(5);
#A = [22 21 -8 4; 21 49 11 39; -8 11 60 -19; 4 39 -19 135]
@time λₘₐₓ = power_eigen(A, 10);
print(λₘₐₓ)
e, v = eigen(A)

  0.000020 seconds (27 allocations: 3.219 KiB)
[141.77545249026366]

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
5-element Array{Float64,1}:
 -34.50244427098533
   7.642985119979592
  19.176923313776378
  36.907083346956085
 141.77545249027293
vectors:
5×5 Array{Float64,2}:
  0.689578   0.189777   -0.234934  -0.0581557  -0.655661
 -0.283217  -0.145227    0.485928  -0.675547   -0.4541
 -0.136724   0.0934614   0.571198   0.70626    -0.384059
 -0.511222   0.77221    -0.31884   -0.049606   -0.19551
 -0.405252  -0.581249   -0.529862   0.197459   -0.42211

Jak widać z wyniku wykonania powyższego kodu, uzyskaliśmy największą co do modułu wartość własną macierzy. Ta wartość zgadza sięz wartością otrzymaną za pomocą metody eigen(A). Za pomocą metody potęgowej można również wyznaczyć najmniejszą co do modułu wartość własną macierzy. Korzysta się z twierdzenia dotyczącego przesunięcia spektrum macierzy:<br />
### "Jeżeli $\lambda$ jest wartością własną macierzy A, to $\lambda + r$ jest wartością własną macierzy $A + \tau I$"
Należy pamiętać, że twierdzenie ma zastosowanie dla macierzy symetrycznych i dodatnio określonych. Po zastosowaniu przesunięcia $B = A - \lambda_{max}I$ można ponownie zastosować metodę iteracji prostej dla macierzy B zbieżną do największej co do modułu wartości własnej $\lambda = \lambda_{min}-\lambda_{max}$. Stąd można wyznaczyć $\lambda_{min}$.

In [73]:
I = diagonal_matrix(size(A,1))
# B = A - λₘₐₓ .* I
# λ = power_eigen(B, 10);
# λₘᵢₙ = λ + λₘₐₓ
# print(λₘᵢₙ)
λₘᵢₙ = power_eigen_min(A,20)

1×1 Array{Float64,2}:
 7.6429851199796

Mając największą i najmniejszą wartość własną macierzy, można wyznaczyć współczynnik uwarunkowania macierzy:
$$cond(A)=\sqrt{\frac{\lambda_{max}(A^TA)}{\lambda_{min}(A^TA)}}$$
We wzorze przyjęto, że macierz A jest symetryczna, co oznacza, że $A=A^T$, ewentualnie można macierz wejściową doprowadzić do postaci symetrycznej stosując wzór $B = A^TA$

In [74]:
value = custom_cond(λₘₐₓ, λₘᵢₙ)
print(value)

√cond(A)


[4.306941907538402]

4.306941907538545