In [1]:
using LinearAlgebra
using Statistics

In [47]:
# helper methods
function symetric_matrix(dim::Integer)::Matrix
    A = ones(dim,dim);
    for i = 1:dim
        for j = 1:dim
            A[i,j] = rand(-50:50);
            A[j,i] = A[i,j];
        end
    end
    return A;
end

function random_matrix(dim::Integer)::Matrix
    A = ones(dim, dim);
    for i = 1:dim
        for j = 1:dim
            A[i,j] = rand(-50:50)
        end
    end
    return A
end

function diagonal_matrix(dim::Integer)::Matrix
    I = ones(dim,dim)
    return Diagonal(I)
end

function custom_cond(λₘₐₓ, λₘᵢₙ)
    return √(λₘₐₓ/λₘᵢₙ)
end

custom_cond (generic function with 1 method)

Poniżej przygotowana jest funkcja do metody iteracji prostej (metoda potęgowa), dzięki której można wyznaczyć największą co do modułu wartość własną, czyli promień spektralny macierzy, który opisany jest wzorem:
## $$\rho(A) = |\lambda_{max}| = \lim_{i \to \infty} \frac{||t_{i+1}||_{\infty}}{||t_{i}||_{\infty}}$$

Przy założeniu, że dowolny wektor początkowy t_{0} != 0, do uzyskania promienia spektralnego prowadzą iteracje postaci:
## $$t_{i+1} = At_{i},\ i=0,1,2...$$



In [13]:
# metoda potegowa
function power_eigen(A::Matrix, iterations::Integer)::Array
    n = size(A, 1);
    X = ones(n,1);
    for i = 1:iterations
        X = A * X;
        X = X / norm(X);
    end

    return X' * A * X / (X' * X);
end

power_eigen (generic function with 1 method)

In [55]:
A = symetric_matrix(5);
A = [22 21 -8 4; 21 49 11 39; -8 11 60 -19; 4 39 -19 135]
@time λₘₐₓ = power_eigen(A, 10);
print(λₘₐₓ)
e, v = eigen(A)

  0.000024 seconds (67 allocations: 5.062 KiB)
[153.28186736316832]

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
4-element Array{Float64,1}:
   3.70543724605281
  42.11575140376253
  66.89693680190882
 153.28187454827614
vectors:
4×4 Array{Float64,2}:
 -0.743357   0.657847  -0.0776098   0.0929174
  0.576177   0.542734  -0.503278    0.346656
 -0.282124  -0.398303  -0.858991   -0.154579
 -0.189329  -0.337687   0.0531173   0.92049

Jak widać z wyniku wykonania powyższego kodu, uzyskaliśmy największą co do modułu wartość własną macierzy. Ta wartość zgadza sięz wartością otrzymaną za pomocą metody eigen(A). Za pomocą metody potęgowej można również wyznaczyć najmniejszą co do modułu wartość własną macierzy. Korzysta się z twierdzenia dotyczącego przesunięcia spektrum macierzy:<br />
### "Jeżeli $\lambda$ jest wartością własną macierzy A, to $\lambda + r$ jest wartością własną macierzy $A + \tau I$"
Po zastosowaniu przesunięcia $B = A - \lambda_{max}I$ można ponownie zastosować metodę iteracji prostej dla macierzy B zbieżną do największej co do modułu wartości własnej $\lambda = \lambda_{min}-\lambda_{max}$. Stąd można wyznaczyć $\lambda_{min}$.

In [56]:
I = diagonal_matrix(size(A,1))
B = A - λₘₐₓ .* I
@time λ = power_eigen(B, 10);
λₘᵢₙ = λ + λₘₐₓ

  0.000030 seconds (27 allocations: 2.875 KiB)


1×1 Array{Float64,2}:
 3.7641649496202376

Mając największą i najmniejszą wartość własną macierzy, można wyznaczyć współczynnik uwarunkowania macierzy:
$$cond(A)=\sqrt{\frac{\lambda_{max}(A^TA)}{\lambda_{min}(A^TA)}}$$
We wzorze przyjęto, że macierz A jest symetryczna, co oznacza, że $A=A^T$, ewentualnie można macierz wejściową doprowadzić do postaci symetrycznej stosując wzór $B = A^TA$

In [57]:
value = custom_cond(λₘₐₓ, λₘᵢₙ)
print(value)

√cond(A)


[6.381328002505951]

6.431698388238534